apiVersion: v1
kind: Service
metadata:
  labels:
  name: haproxy-stats
  namespace: ingress-system
spec:
  selector:
    run: haproxy-ingress
  ports:
  - name: stats
    protocol: TCP
    port: 1024
    targetPort: 1024
    nodePort: 30000
  type: NodePort