apiVersion: v1
kind: Service
metadata:
  name: manual-00
  namespace: tenants
spec:
  ports:
  - name: apiserver
    port: 6443
    protocol: TCP
    targetPort: 6443
  - name: proxyserver
    port: 8132
    protocol: TCP
    targetPort: 8132
  selector:
    kamaji.clastix.io/soot: manual-00
  type: LoadBalancer
